# Generated by Django 2.1.7 on 2019-03-15 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='thread_TillExpire',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='threads',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 19, 46, 48, 153826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='threads',
            name='thread_Expire',
            field=models.CharField(default='10 mins', max_length=200),
        ),
        migrations.AlterField(
            model_name='threads',
            name='thread_Exposer',
            field=models.CharField(default='public', max_length=200),
        ),
    ]
