# Generated by Django 2.1.7 on 2019-03-15 23:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threadApp', '0003_auto_20190315_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 19, 49, 12, 829979, tzinfo=utc)),
        ),
    ]
