# Generated by Django 2.1.7 on 2019-03-12 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_Name', models.CharField(max_length=200)),
                ('thread_Body', models.TextField()),
                ('created_At', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
