# Generated by Django 2.1.7 on 2019-03-16 18:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_Name', models.CharField(max_length=200)),
                ('thread_Body', models.TextField()),
                ('thread_Exposer', models.CharField(default='public', max_length=200)),
                ('thread_Expire', models.CharField(default='10 mins', max_length=200)),
                ('thread_TillExpire', models.CharField(default='', max_length=200)),
                ('created_At', models.DateTimeField(default=datetime.datetime(2019, 3, 16, 14, 32, 31, 250315, tzinfo=utc))),
                ('thread_Owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thread_Owner', to=settings.AUTH_USER_MODEL)),
                ('thread_Share', models.ManyToManyField(blank=True, related_name='thread_Share', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Threads',
            },
        ),
    ]
