# Generated by Django 2.1.7 on 2019-03-16 18:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 14, 56, 34, 352519, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='threads',
            name='thread_Share',
        ),
        migrations.AddField(
            model_name='threads',
            name='thread_Share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
