# Generated by Django 2.1.7 on 2019-03-16 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadApp', '0002_auto_20190316_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 15, 42, 34, 734720, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='threads',
            name='thread_Share',
        ),
        migrations.AddField(
            model_name='threads',
            name='thread_Share',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
