# Generated by Django 2.1.7 on 2019-03-14 18:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadApp', '0003_threads_thread_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='thread_Share',
            field=models.ManyToManyField(blank=True, related_name='thread_Share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threads',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='threads',
            name='thread_Owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thread_Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
