# Generated by Django 2.1.7 on 2019-03-16 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threadApp', '0005_auto_20190316_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 16, 41, 13, 607739, tzinfo=utc)),
        ),
    ]
